stages:
  pull_data:
    cmd: mkdir -p data/raw && poetry run kaggle competitions download -c playground-series-s4e12
      && mv playground-series-s4e12.zip data/raw/ && cd data/raw/ && unzip playground-series-s4e12.zip
      && rm playground-series-s4e12.zip
    outs:
    - data/raw

  prepare_basic:
    cmd: poetry run python insurance/prepare_basic.py
    deps:
    - insurance/prepare_basic.py
    - insurance/data_pipeline.py
    params:
    - data.random_state
    outs:
    - data/prepared/train_data.feather
    - data/prepared/test_data.feather
    - out/data_pipeline_train.pkl

  train_layer_0:
    cmd: poetry run python insurance/train_layer.py --layer 0
    params:
    - layer_0
    deps:
    - data/prepared/train_data.feather
    - data/prepared/test_data.feather
    - insurance/train_layer.py
    outs:
    - data/oof/layer_0.feather
    - data/preds/layer_0.feather

  train_layer_1:
    cmd: poetry run python insurance/train_layer.py --layer 1
    params:
    - layer_1
    deps:
    - data/oof/layer_0.feather
    - data/preds/layer_0.feather
    - insurance/train_layer.py
    outs:
    - data/oof/layer_1.feather
    - data/preds/layer_1.feather

  train_ensemble:
    cmd: poetry run python insurance/train_ensemble.py --previous-layer 1
    params:
    - ensemble
    deps:
    - data/oof/layer_1.feather
    - data/preds/layer_1.feather
    - insurance/train_ensemble.py
    outs:
    - out/data_pipeline_train_ensemble.pkl
    - out/preds.csv # Final submission to kaggle


metrics:
- dvclive/xgboost_simple_layer_0/metrics.json
- dvclive/xgboost_layer_1/metrics.json
- dvclive/xgboost_layer_0/metrics.json
- dvclive/catboost_layer_0/metrics.json
- dvclive/lgbm_layer_0/metrics.json
- dvclive/lgbm_simple_layer_0/metrics.json
- dvclive/catboost_layer_1/metrics.json
- dvclive/lgbm_layer_1/metrics.json
- dvclive/ensemble/metrics.json
plots:
- dvclive/xgboost_simple_layer_0/plots/metrics:
    x: step
- dvclive/xgboost_simple_layer_0/plots/custom/XGBoost CV Loss Layer 0.json:
    template: linear
    x: booster
    y:
    - train-rmse-mean
    - test-rmse-mean
    x_label: RMSLE
    y_label: Booster
- dvclive/xgboost_layer_1/plots/metrics:
    x: step
- dvclive/xgboost_layer_1/plots/custom/XGBoost CV Loss Layer 1.json:
    template: linear
    x: booster
    y:
    - train-rmse-mean
    - test-rmse-mean
    x_label: RMSLE
    y_label: Booster
- dvclive/xgboost_layer_0/plots/metrics:
    x: step
- dvclive/xgboost_layer_0/plots/custom/XGBoost CV Loss Layer 0.json:
    template: linear
    x: booster
    y:
    - train-rmse-mean
    - test-rmse-mean
    x_label: Booster
    y_label: RMSLE
- dvclive/catboost_layer_0/plots/metrics:
    x: step
- dvclive/catboost_layer_0/plots/custom/Catboost CV Loss 0.json:
    template: linear
    x: booster
    y:
    - train-RMSE-mean
    - test-RMSE-mean
    x_label: Booster
    y_label: RMSLE
- dvclive/lgbm_layer_0/plots/metrics:
    x: step
- dvclive/lgbm_layer_0/plots/custom/LGBM CV Loss 0.json:
    template: linear
    x: x
    y:
    - valid rmse-mean
    x_label: Booster
    y_label: RMSLE
- dvclive/lgbm_simple_layer_0/plots/metrics:
    x: step
- dvclive/lgbm_simple_layer_0/plots/custom/LGBM CV Loss 0.json:
    template: linear
    x: x
    y:
    - valid rmse-mean
    x_label: Booster
    y_label: RMSLE
- dvclive/catboost_layer_1/plots/metrics:
    x: step
- dvclive/catboost_layer_1/plots/custom/Catboost CV Loss 1.json:
    template: linear
    x: booster
    y:
    - train-RMSE-mean
    - test-RMSE-mean
    x_label: Booster
    y_label: RMSLE
- dvclive/lgbm_layer_1/plots/metrics:
    x: step
- dvclive/lgbm_layer_1/plots/custom/LGBM CV Loss 1.json:
    template: linear
    x: x
    y:
    - valid rmse-mean
    x_label: Booster
    y_label: RMSLE
- dvclive/ensemble/plots/metrics:
    x: step
