stages:
  pull_data:
    cmd: mkdir -p data/raw && poetry run kaggle competitions download -c playground-series-s4e12
      && mv playground-series-s4e12.zip data/raw/ && cd data/raw/ && unzip playground-series-s4e12.zip
      && rm playground-series-s4e12.zip
    outs:
    - data/raw

  prepare_basic:
    cmd: poetry run python insurance/prepare_basic.py
    deps:
    - insurance/prepare_basic.py
    params:
    - data.random_state
    outs:
    - data/prepared/prepared_data.feather


  train_layer_0:
    foreach:
    - xgboost
    - catboost
    - lgbm
    do:
      cmd: poetry run python insurance/train_${item}.py --layer 0 --layer 0
      deps:
      - data/prepared/prepared_data.feather
      - insurance/data_pipeline.py
      - insurance/train_${item}.py
      outs:
      - out/data_pipeline_train_${item}.pkl
      - out/models/${item}_model_layer_0.pkl
      - data/oof/${item}_layer_0.feather

  train_layer_1:
    foreach:
    - xgboost
    - catboost
    - lgbm
    do:
      cmd: poetry run python insurance/train_${item}.py --layer 1
      deps:
      - data/oof/xgboost_layer_0.feather
      - data/oof/catboost_layer_0.feather
      - data/oof/lgbm_layer_0.feather
      - insurance/train_${item}.py
      outs:
      - out/models/${item}_model_layer_1.pkl
      - data/oof/${item}_layer_1.feather

  train_ensemble:
    cmd: poetry run python insurance/train_ensemble.py --previous-layer 1
    deps:
    - data/oof/xgboost_layer_1.feather
    - data/oof/catboost_layer_1.feather
    - data/oof/lgbm_layer_1.feather
    - insurance/train_ensemble.py
    outs:
    - out/data_pipeline_train_ensemble.pkl



metrics:
- dvclive/lgbm_layer_0/metrics.json
- dvclive/catboost_layer_0/metrics.json
- dvclive/lgbm_layer_1/metrics.json
- dvclive/catboost_layer_1/metrics.json
- dvclive/ensemble/metrics.json
- dvclive/xgboost_layer_0/metrics.json
- dvclive/xgboost_layer_1/metrics.json
plots:
- dvclive/lgbm_layer_0/plots/metrics:
    x: step
- dvclive/lgbm_layer_0/plots/custom/LGBM CV Loss.json:
    template: linear
    x: x
    y:
    - valid rmse-mean
    x_label: RMSLE
    y_label: Booster
- dvclive/catboost_layer_0/plots/metrics:
    x: step
- dvclive/catboost_layer_0/plots/custom/Catboost CV Loss.json:
    template: linear
    x: booster
    y:
    - train-RMSE-mean
    - test-RMSE-mean
    x_label: RMSLE
    y_label: Booster
- dvclive/lgbm_layer_1/plots/metrics:
    x: step
- dvclive/lgbm_layer_1/plots/custom/LGBM CV Loss.json:
    template: linear
    x: x
    y:
    - valid rmse-mean
    x_label: RMSLE
    y_label: Booster
- dvclive/catboost_layer_1/plots/metrics:
    x: step
- dvclive/catboost_layer_1/plots/custom/Catboost CV Loss.json:
    template: linear
    x: booster
    y:
    - train-RMSE-mean
    - test-RMSE-mean
    x_label: RMSLE
    y_label: Booster
- dvclive/ensemble/plots/metrics:
    x: step
- dvclive/xgboost_layer_0/plots/metrics:
    x: step
- dvclive/xgboost_layer_0/plots/custom/XGBoost CV Loss Layer 0.json:
    template: linear
    x: booster
    y:
    - train-rmse-mean
    - test-rmse-mean
    x_label: RMSLE
    y_label: Booster
- dvclive/xgboost_layer_1/plots/metrics:
    x: step
- dvclive/xgboost_layer_1/plots/custom/XGBoost CV Loss Layer 1.json:
    template: linear
    x: booster
    y:
    - train-rmse-mean
    - test-rmse-mean
    x_label: RMSLE
    y_label: Booster
