stages:
  pull_data:
    cmd: mkdir -p data/raw && poetry run kaggle competitions download -c playground-series-s4e12
      && mv playground-series-s4e12.zip data/raw/ && cd data/raw/ && unzip playground-series-s4e12.zip
      && rm playground-series-s4e12.zip
    outs:
    - data/raw

  prepare_basic:
    cmd: poetry run python insurance/prepare_basic.py
    deps:
    - insurance/prepare_basic.py
    params:
    - data.random_state
    outs:
    - data/prepared/prepared_data.csv

  train_basic:
    cmd: poetry run python insurance/train_basic.py
    deps:
    - insurance/train_basic.py
    - data/prepared/prepared_data.csv
    outs:
    - out/models/model_basic.pkl

metrics:
- out/metrics.json
plots:
- out/plots/metrics:
    x: step
