data:
  random_state: 42

layer_0:
  xgboost:
    type: xgboost
    params:
      n_estimators: 500
      learning_rate: 0.3
      max_depth: 5
      reg_lambda: 1
      reg_alpha: 0.1
      random_state: 42
      # num_leaves: None
      # min_child_weight: 1
      objective: reg:squarederror
      eval_metric: rmse
      device: cuda
      # tree_method: hist
      verbosity: 0
      enable_categorical: True
  # xgboost_simple:
  #   type: xgboost
  #   params:
  #     n_estimators: 50
  #     learning_rate: 0.25
  #     random_state: 24
  #     objective: reg:squarederror
  #     eval_metric: rmse
  #     # device: cuda
  #     verbosity: 0
  #     enable_categorical: True 
  catboost:
    type: catboost
    params:
      iterations: 200
      learning_rate: 0.33741802035300733
      depth: 5
      l2_leaf_reg: 0.6988750565188863
      loss_function: "RMSE"
      random_strength: 0.001326565507721897
      bagging_temperature: 0.5233508452963999
      task_type: GPU
  lgbm:
    type: lgbm
    params:
      objective: regression
      metric: rmse
      feature_pre_filter: False
      lambda_l1: 1.6575159147685196e-08
      lambda_l2: 0.0017415507514917511
      num_leaves: 67
      feature_fraction: 1.0
      bagging_fraction: 1.0
      bagging_freq: 0
      min_child_samples: 20
  lgbm_simple: 
    type: lgbm
    params:
      objective: regression
      metric: rmse
      feature_pre_filter: False

layer_1:
  # xgboost:
  #   type: xgboost
  #   params:
  #     random_state: 12
  #     objective: reg:squarederror
  #     eval_metric: rmse
  #     device: cuda
  #     verbosity: 0
  #     enable_categorical: True
  catboost:
    type: catboost
    params:
      iterations: 600
      loss_function: RMSE
      task_type: GPU
      random_seed: 12
  lgbm: 
    type: lgbm
    params:
      objective: regression
      metric: rmse
      feature_pre_filter: False

ensemble:
  random_state: 42