data:
  random_state: 42

train:
  random_state: 42 
  n_splits: 5
  xgboost:
    random_state: 42
    device: cuda
    objective: reg:squarederror
    eval_metric: rmse
    booster: gbtree
    lambda: 6.843302774035178e-05
    alpha: 0.006258449730947676
    subsample: 0.901647304077349
    colsample_bytree: 0.922549532305334
    max_depth: 5
    min_child_weight: 9
    eta: 0.4802025848144224
    gamma: 0.01363825229793838
    grow_policy: lossguide
  basic:

torch_imputer:
  epochs: 10
  lr: 1e-3
  batch_size: 32