data:
  random_state: 42

train:
  random_state: 42 
  n_splits: 5
  xgboost:
    random_state: 42
    device: cuda
    objective: reg:squarederror
    eval_metric: rmse
    booster: gbtree
    lambda: 0.4104749889610154
    alpha: 5.561529990659439e-07
    subsample: 0.9814736188143719
    colsample_bytree: 0.7240915982708991
    max_depth: 7
    min_child_weight: 9
    eta: 0.4324358241129275
    gamma: 2.865477838059048e-06
    grow_policy: depthwise
  basic:

torch_imputer:
  epochs: 50
  lr: 1e-3
  batch_size: 2048